### ISSUE TITLE
docker-compose.yml of  it-tools  is error 

### ISSUE THREAD

**Issue by luojiyin1987** [einverne/dockerfile#3]
https://github.com/einverne/dockerfile/blob/master/it-tools/docker-compose.yml
it should be 
```yaml
version: '3.3'

services:
   corentinth:
      container_name: it-tools
      image: 'ghcr.io/corentinth/it-tools:latest'
      restart: unless-stopped
      ports:
        - '8080:80'
```
